import { Request, Response } from 'express';
import * as itemService from '../services/item.service';


export const getItems = async (req: Request, res: Response) => {
    try {
        const { search } = req.query;
        const items = await itemService.getItems(
            search as string
        );
        res.json(items);
    } catch (error: any) {
        res.status(500).json({ error: error.message });
    }
};

export const getItemById = async (req: Request, res: Response) => {
    try {
        const item = await itemService.getItemById(req.params.id);
        if (!item) {
            return res.status(404).json({ error: 'Item not found' });
        }
        res.json(item);
    } catch (error: any) {
        res.status(500).json({ error: error.message });
    }
};

export const createItem = async (req: Request, res: Response) => {
    try {
        const rawData = req.body;

        const data = {
            name: rawData.name,
            id: rawData.id // Pass the ITM-XXX id if generated by frontend
        };

        const item = await itemService.createItem(data);
        res.status(201).json(item);
    } catch (error: any) {
        res.status(500).json({ error: error.message });
    }
};

export const updateItem = async (req: Request, res: Response) => {
    try {
        const rawData = req.body;
        
        const data = {
            ...(rawData.name ? { name: rawData.name } : {}),
        };

        const item = await itemService.updateItem(req.params.id, data);
        res.json(item);
    } catch (error: any) {
        res.status(500).json({ error: error.message });
    }
};

export const deleteItem = async (req: Request, res: Response) => {
    try {
        await itemService.deleteItem(req.params.id);
        res.status(204).send();
    } catch (error: any) {
        res.status(500).json({ error: error.message });
    }
};
